### ISSUE TITLE
Is there a way to color the Sparkline in gtExtras?

### ISSUE THREAD

**Issue by wagathu** [jthomasmock/gtExtras#103]
I raised the same question on [SO](https://stackoverflow.com/questions/77185930/is-there-a-way-to-color-the-sparkline-in-gtextras?noredirect=1#comment136072506_77185930)
 
I am working on a gtExtras table with the following example

```
library(gt)
library(gtExtras)
library(dplyr)

dd <- data.frame(
  where = c("where1", "where2", "where3", "where4"),
  "year_2014" = c(30, 60, 20, 10),
  "year_2022" = c(10, 50, 30, 20)) 

dd |> rowwise() |>
  mutate(change = list(c(year_2014, year_2022))) |>
  gt() |>
  gt_plt_sparkline(change, label = FALSE)
```

I intend to color the Sparkline (the full Sparkline and not the end, as it in the default) depending on whether there was a decrease "green" or an increase "red".

How do I proceed?

![image](https://github.com/jthomasmock/gtExtras/assets/108395924/cbdc378c-7962-4c35-8746-bf8f3a106148)

**Comment by jthomasmock** [comment]
Howdy! Thanks for the feature request.

I don't currently have plans to enable this feature because "change" is relatively arbitrary, because are we just looking at the first vs last? The overall trend? Or some other constraint.

I think a better option is user defined value that indicate increases or decreases, such as:

```r
library(gt)
library(gtExtras)
library(dplyr)

dd <- data.frame(
  where = c("where1", "where2", "where3", "where4"),
  "year_2014" = c(30, 60, 20, 10),
  "year_2022" = c(10, 50, 30, 20)) 

dd |> rowwise() |>
  mutate(change = list(c(year_2014, year_2022))) |>
  mutate(dir = last(change)- first(change)) |>
  gt() |>
  gt_plt_sparkline(change, label = FALSE) |> 
  gtExtras::gt_fa_rank_change(
    column = dir, font_color = "match"
  )
```

![image](https://github.com/jthomasmock/gtExtras/assets/29187501/ca06c6ad-2460-4871-9a2b-3781f7323e4b)

**Comment by jthomasmock** [comment]
Closing as not planned
