### ISSUE TITLE
Option to adjust height of `gt_plt_winloss()`

### ISSUE THREAD

**Issue by cxinya** [jthomasmock/gtExtras#64]
Thank you so much for making one of my favorite packages that makes my job easier almost every day! 

It'd be helpful to add an option to control the height of the pills/squares in the `gt_plt_winloss()` function. In my case, I have a table with multi-line rows and the default pills appear a little small in their cells. It'd be great to be able to control height in addition to width.

```
gt_plt_winloss <- function(gt_object, column, max_wins = 17,
                           palette = c("#013369", "#D50A0A", "gray"),
                           type = "pill", width = max_wins/0.83,
                           height = 3.81) {
...

ggsave(out_name, plot = plot_out,
           dpi = 20, height = height, width = width, units = "mm")
```

**Comment by jthomasmock** [comment]
Howdy! Thanks for the feature request - do you have a minimal reprex example table that I can reference?

**Comment by cxinya** [comment]
Yes! Thanks for taking a look. I'd love to make the pills just a little taller for rows like this.
```
library(dplyr)
library(gt)
library(gtExtras)

tibble(
  x = "check<br>out<br>all<br>this<br>fab<br>data",
  y = c(0, .5, 1)
) %>% 
  group_by(x) %>% 
  summarize(y = list(y)) %>% 
  gt() %>% 
  gt_plt_winloss(y, max_wins = 3) %>% 
  fmt_markdown(x)
```
![image](https://user-images.githubusercontent.com/30631351/189131116-ce8c90aa-cc49-4fd9-b9e9-dcfcdc1c38e8.png)

**Comment by jthomasmock** [comment]
Thanks for the reprex!

I've optimized all of the opinionated inline plots as essentially sparkline extensions, meaning they are all specifically written to take up as little vertical/horizontal space as possible. I try to be careful to not veer away from that, as otherwise I'm tasked with implementing one-off plots or failing to optimize, rather than the core focus of inline, minimalistic plots. Changing the overall scaling of winloss plots would be rather complex and could vary by HOW much vertical space do we need?

With the example you have - the overall scaling would be a problem - the plot would need to be both much wider and taller. If you want to optimize for a much different scale I'd recommend implementing it with `ggplot2` itself.

 A brief example below:

```
library(ggplot2)
library(dplyr)
library(gt)

df_ex <- tibble(
  x = "check<br>out<br>all<br>this<br>fab<br>data",
  y = c(0, .5, 1)
) %>%
  group_by(x) %>%
  summarize(y = list(y))

my_ggplot <- function(vals) {
  df_gg <- data.frame(
    x = 1:length(vals),
    y = vals,
    color = dplyr::case_when(
      vals == 0.5 ~ "grey", 
      vals == 1 ~ "blue", 
      vals == 0 ~ "red")
    )
  print(df_gg$color)
  ggplot(df_gg, aes(x = x)) +
    geom_point(aes(y = y, fill = I(color), color = I(color)), 
               shape = 15, size = 40) +
    theme_void() +
    scale_x_continuous(limits = c(0.5, length(vals) + 0.5)) +
    scale_y_continuous(limits = c(-0.1, 1.1))
}

ex_plot <- my_ggplot(df_ex$y |> unlist())

df_ex |> 
  gt() |> 
  text_transform(
    locations = cells_body(y),
    fn = function(x){
      ggplot_image(ex_plot, aspect_ratio = 0.75)
    }
  ) |> 
  fmt_markdown(x)
```

<img src="https://user-images.githubusercontent.com/29187501/189693767-d33bdc9b-c786-42ae-a224-f96544e45433.png" width=250></img>

**Comment by jthomasmock** [comment]
If you have some additional feedback, please let me know - otherwise going to close this one out for now. Thanks!
